import connectDB from "@/lib/db";
import Product from "@/models/Product";
import { NextResponse } from "next/server";

export async function GET() {
  try {
    await connectDB();
    await Product.deleteMany();

    await Product.insertMany([
      {
        title: "Wireless Noise-Cancelling Headphones",
        description: "Premium over-ear headphones with active noise cancellation and 30-hour battery life.",
        price: 299,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
        category: "Electronics",
      },
      {
        title: "Mechanical Gaming Keyboard",
        description: "RGB backlit mechanical keyboard with Cherry MX switches for ultimate gaming performance.",
        price: 149,
        image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=400",
        category: "Electronics",
      },
      {
        title: "4K Ultra HD Smart TV 55\"",
        description: "55-inch 4K Smart TV with HDR, Dolby Vision, and built-in streaming apps.",
        price: 799,
        image: "https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=400",
        category: "Electronics",
      },
      {
        title: "Portable Bluetooth Speaker",
        description: "Waterproof portable speaker with 360-degree sound and 12-hour playtime.",
        price: 89,
        image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400",
        category: "Electronics",
      },
      {
        title: "Smartphone Stand & Wireless Charger",
        description: "15W fast wireless charger with adjustable phone stand for all Qi-enabled devices.",
        price: 45,
        image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400",
        category: "Electronics",
      },
      {
        title: "Men's Running Shoes",
        description: "Lightweight and breathable running shoes with cushioned sole for maximum comfort.",
        price: 120,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        category: "Footwear",
      },
      {
        title: "Women's Yoga Pants",
        description: "High-waist stretch yoga pants with moisture-wicking fabric for all-day comfort.",
        price: 55,
        image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400",
        category: "Clothing",
      },
      {
        title: "Classic Leather Wallet",
        description: "Slim genuine leather bifold wallet with RFID blocking technology.",
        price: 39,
        image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
        category: "Accessories",
      },
      {
        title: "Stainless Steel Watch",
        description: "Elegant stainless steel watch with sapphire crystal glass and 50m water resistance.",
        price: 199,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
        category: "Accessories",
      },
      {
        title: "Leather Crossbody Bag",
        description: "Stylish genuine leather crossbody bag with multiple compartments.",
        price: 85,
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
        category: "Bags",
      },
      {
        title: "Stainless Steel Water Bottle",
        description: "Double-wall insulated water bottle that keeps drinks cold for 24 hours.",
        price: 35,
        image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        category: "Kitchen",
      },
      {
        title: "Coffee Maker Machine",
        description: "12-cup programmable coffee maker with built-in grinder and thermal carafe.",
        price: 129,
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
        category: "Kitchen",
      },
      {
        title: "Non-Stick Cooking Pan Set",
        description: "5-piece non-stick cookware set with heat-resistant handles.",
        price: 79,
        image: "https://images.unsplash.com/photo-1584990347449-a2d4c2c044c9?w=400",
        category: "Kitchen",
      },
      {
        title: "Air Fryer 5.8Qt",
        description: "Large capacity air fryer with digital display and 8 preset cooking functions.",
        price: 99,
        image: "https://images.unsplash.com/photo-1648146325776-28bbfb08b34e?w=400",
        category: "Kitchen",
      },
      {
        title: "Yoga Mat",
        description: "Extra thick non-slip yoga mat with alignment lines and carrying strap.",
        price: 45,
        image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=400",
        category: "Sports",
      },
      {
        title: "Adjustable Dumbbell Set",
        description: "Space-saving adjustable dumbbells ranging from 5 to 52.5 lbs.",
        price: 349,
        image: "https://images.unsplash.com/photo-1590487988256-9ed24133863e?w=400",
        category: "Sports",
      },
      {
        title: "Mountain Bike Helmet",
        description: "Lightweight mountain bike helmet with 18 vents and adjustable fit system.",
        price: 65,
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
        category: "Sports",
      },
      {
        title: "Camping Tent 4-Person",
        description: "Waterproof 4-person camping tent with easy setup and ventilation system.",
        price: 189,
        image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400",
        category: "Outdoors",
      },
      {
        title: "Hiking Backpack 50L",
        description: "50L waterproof hiking backpack with multiple compartments and ergonomic straps.",
        price: 110,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        category: "Outdoors",
      },
      {
        title: "Sunglasses Polarized",
        description: "UV400 polarized sunglasses with lightweight frame for outdoor activities.",
        price: 59,
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
        category: "Accessories",
      },
      {
        title: "Scented Candle Set",
        description: "Set of 6 hand-poured soy wax candles with natural essential oil fragrances.",
        price: 42,
        image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=400",
        category: "Home Decor",
      },
      {
        title: "Throw Blanket",
        description: "Super soft sherpa throw blanket, perfect for couch or bed use.",
        price: 38,
        image: "https://images.unsplash.com/photo-1580301762395-073aaafcf939?w=400",
        category: "Home Decor",
      },
      {
        title: "Indoor Plant Pot Set",
        description: "Set of 3 ceramic plant pots with drainage holes in modern minimalist design.",
        price: 32,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400",
        category: "Home Decor",
      },
      {
        title: "Desk Lamp LED",
        description: "Adjustable LED desk lamp with USB charging port and 5 brightness levels.",
        price: 49,
        image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400",
        category: "Home Decor",
      },
      {
        title: "Wooden Chess Set",
        description: "Handcrafted wooden chess set with storage drawer and felted bottom pieces.",
        price: 55,
        image: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400",
        category: "Toys & Games",
      },
      {
        title: "LEGO Architecture Set",
        description: "1500-piece LEGO architecture set for building famous world landmarks.",
        price: 119,
        image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        category: "Toys & Games",
      },
      {
        title: "Watercolor Paint Set",
        description: "Professional 48-color watercolor paint set with brushes and mixing palette.",
        price: 35,
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
        category: "Art & Craft",
      },
      {
        title: "Acoustic Guitar",
        description: "Full-size acoustic guitar with spruce top and mahogany back, perfect for beginners.",
        price: 189,
        image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400",
        category: "Music",
      },
      {
        title: "Wireless Gaming Mouse",
        description: "Ultra-lightweight wireless gaming mouse with 25K DPI sensor and 70-hour battery.",
        price: 79,
        image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400",
        category: "Electronics",
      },
      {
        title: "USB-C Hub 7-in-1",
        description: "7-in-1 USB-C hub with 4K HDMI, 100W PD charging, and SD card reader.",
        price: 55,
        image: "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=400",
        category: "Electronics",
      },
      {
        title: "Skincare Face Serum",
        description: "Vitamin C brightening face serum with hyaluronic acid for glowing skin.",
        price: 48,
        image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400",
        category: "Beauty",
      },
      {
        title: "Electric Toothbrush",
        description: "Sonic electric toothbrush with 5 cleaning modes and 2-minute smart timer.",
        price: 69,
        image: "https://images.unsplash.com/photo-1559591937-abc9b3a0e5a9?w=400",
        category: "Beauty",
      },
      {
        title: "Hair Dryer Professional",
        description: "1875W professional ionic hair dryer with diffuser and concentrator attachments.",
        price: 89,
        image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400",
        category: "Beauty",
      },
      {
        title: "Perfume Eau de Parfum",
        description: "Long-lasting floral perfume with notes of jasmine, rose, and sandalwood.",
        price: 75,
        image: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=400",
        category: "Beauty",
      },
      {
        title: "Notebook Journal Set",
        description: "Set of 3 hardcover dot grid notebooks, perfect for journaling and note-taking.",
        price: 28,
        image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400",
        category: "Stationery",
      },
      {
        title: "Fountain Pen Set",
        description: "Premium fountain pen set with 6 ink cartridges in a gift box.",
        price: 45,
        image: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400",
        category: "Stationery",
      },
      {
        title: "Mechanical Pencil Set",
        description: "Set of 5 drafting mechanical pencils with different lead sizes.",
        price: 22,
        image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
        category: "Stationery",
      },
      {
        title: "Protein Powder Chocolate",
        description: "Whey protein powder with 25g protein per serving, chocolate flavor.",
        price: 59,
        image: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400",
        category: "Health",
      },
      {
        title: "Vitamin D3 Supplements",
        description: "High potency Vitamin D3 2000IU supplements, 365 softgels.",
        price: 18,
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Health",
      },
      {
        title: "Resistance Bands Set",
        description: "Set of 5 resistance bands with different tension levels for full body workout.",
        price: 29,
        image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400",
        category: "Sports",
      },
      {
        title: "Polaroid Instant Camera",
        description: "Instant film camera with built-in flash and selfie mirror, includes film pack.",
        price: 99,
        image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400",
        category: "Electronics",
      },
      {
        title: "Succulent Plant Collection",
        description: "Collection of 6 assorted live succulents in decorative pots.",
        price: 36,
        image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400",
        category: "Home Decor",
      },
      {
        title: "Bamboo Cutting Board Set",
        description: "Set of 3 bamboo cutting boards in different sizes with juice groove.",
        price: 34,
        image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
        category: "Kitchen",
      },
      {
        title: "Smart Fitness Tracker",
        description: "Fitness tracker with heart rate monitor, sleep tracking, and 7-day battery life.",
        price: 79,
        image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400",
        category: "Electronics",
      },
      {
        title: "Denim Jacket",
        description: "Classic unisex denim jacket with button closure and chest pockets.",
        price: 75,
        image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400",
        category: "Clothing",
      },
      {
        title: "Wool Knit Sweater",
        description: "Cozy merino wool knit sweater available in multiple colors.",
        price: 89,
        image: "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=400",
        category: "Clothing",
      },
      {
        title: "Leather Boots",
        description: "Genuine leather ankle boots with rubber sole, perfect for any season.",
        price: 145,
        image: "https://images.unsplash.com/photo-1542621334-a254cf47733d?w=400",
        category: "Footwear",
      },
      {
        title: "Travel Luggage 28\"",
        description: "Hardshell spinner luggage with TSA lock and expandable design.",
        price: 159,
        image: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=400",
        category: "Bags",
      },
      {
        title: "Book: Atomic Habits",
        description: "Bestselling self-improvement book on building good habits and breaking bad ones.",
        price: 18,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        category: "Books",
      },
      {
        title: "Jigsaw Puzzle 1000 Pieces",
        description: "1000-piece jigsaw puzzle featuring a beautiful landscape artwork.",
        price: 24,
        image: "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        category: "Toys & Games",
      },
    ]);

    return NextResponse.json({ message: "Database seeded successfully with 50 products!" });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}